CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS '${DB_WP_USER}'@'%' IDENTIFIED by '${DB_WP_PASSWORD}';
GRANT ALL PRIVILEGES ON wordpress.* TO '${DB_WP_USER}'@'%' WITH GRANT OPTION;
SET PASSWORD FOR 'root'@'localhost'=PASSWORD('${DB_ADMIN_PASSWORD}');
FLUSH PRIVILEGES;
QUIT
