CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS '$WP_NAME'@'%' IDENTIFIED by '$WP_PASSWORD';
GRANT ALL PRIVILEGES ON wordpress.* TO '$WP_NAME'@'%' WITH GRANT OPTION;
SET PASSWORD FOR 'root'@'localhost'=PASSWORD('$USR_PASSWORD');
FLUSH PRIVILEGES;
QUIT
